spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edo
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
settings:
  default-page-number: 0
  default-page-size: 10


